### ISSUE TITLE
Specs misalignment compared to the VSD API responses

### ISSUE THREAD

**Issue by mfagadar** [nuagenetworks/vsd-api-specifications#17]
Dear Nuage team,

I have found several misalignments between the spec files and the real API responses, as follows:

**Nuage R4.0.8**
- _IngressAdvFwdEntryTemplate.spec_ : the _stateful_ attribute is missing

**Nuage R4.0.6 and later**
- _DemarcationService.spec_ : the _priority_ attribute has the wrong type _string_ instead of _integer_
- _DucGroupBinding.spec_ : the _id_ attribute seems to be unused and should be removed
- _location.spec_ : 
  - the _uniqueScope_ property should be set to _null_ instead of _"no"_ for all attributes
  - the _max_value_ and _min_value_ properties of the _latitude_ and _longitude_ attributes need to be in float format (i.e. 90.0 instead of 90)
- _NsRedundantPort.spec_ : 
  - the _uniqueScope_ property should be set to _null_ instead of _"no"_ for all attributes
  - the _max_length_ and _min_length_ properties of the _useUserMnemonic_ attribute need to be null, since the attribute is of _boolean_ type
- _VsgRedundantPort.spec_ : 
  - the _uniqueScope_ property should be set to _null_ instead of _"no"_ for all attributes
  - the _max_length_ and _min_length_ properties of the _useUserMnemonic_ attribute need to be null, since the attribute is of _boolean_ type 

Can you please update the specs so that they reflect the real API responses? Our project relies on them for automatic code generation using the monolithe framework.

Thanks,
Mihai

**Comment by pdellaert** [comment]
@mfagadar: Thank you so much for your clear analysis and help!

I'll take these remarks and create appropriate issues to track these (internally) and make sure with the next release, these should be covered/supported in here.

Some responses:
* `IngressAdvFwdEntryTemplate`: There is not stateful attribute in the API, stateful is not supported for redirection policies or forwarding policies. The UI does wrongfully send a stateful field when creating an `IngressAdvFwdEntryTemplate`, however, it is not returned by the API when fetching an `IngressAdvFwdEntryTemplate`

* `Location`: The `uniqueScope` field is set to null for all attributes already.

* `NsRedundantPort`: The `uniqueScope` field is set to null for all attributes already.

* `VsgRedundantPort`: The `uniqueScope` field is set to null for all attributes already.

BTW, i'm also very interested in what code you generate using the Monolithe framework. We should meet in Antwerp to see how we can better work together

**Comment by mfagadar** [comment]
@pdellaert Thank you for your answer and for the explanations. Looking forward to discuss with you in Antwerp.
 
Just for the record, we found a couple of extra modifications required in the **R4.0.8** branch, as follows:
- _enterprise.spec_ : the _localAS_ attribute's maximum value constraint should be _64534_
- _me.spec_ : the child relation _user_ should have _create_ set to false

**Comment by mfagadar** [comment]
Dear Nuage Team, @pdellaert,

In respect to the **R4.0.8** branch, currently in use by our project, we have found the following additional misalignments: 

- _enterprise_ : set `"create": true` for _patnatpool_ under children
- _ingressaclentrytemplate_ : set `"required": false` for _domainName_, _enterpriseName_ and _ACLTemplateName_ attributes
- _performancemonitor_ : set `"extends": ["@audited", "@base", "@metadata"]` under _model_ 
- _networkmacrogroup_ : set `"relationship": "member"` for the _enterprisenetwork_ under children

Please include the above in the specs update.

All the best,
Mihai

**Comment by pdellaert** [comment]
@mfagadar , thanks
- _enterprise_: this is fixed in 5.0
- _ingressaclentrytemplate_: These fields are not required when creating or updating an entry template, these are automatically filled in by the backend based on which ingressacltemplate you do the POST request
- _performancemonitor_ Thanks, i'll have that checked (sometimes some of those are not needed, i'm pretty sure the metadata does not exist on a performance monitor)
- _networkmacrogroup_: That's a real bad one! Thanks for that, i'll look into that as well

**Comment by hellt** [comment]
afais, `ingressaclentrytemplate` has been fixed in v5.0.1 exactly with these params set to `required: False`

**Comment by mfagadar** [comment]
@pdellaert, another small one in R5.1.1 (there was an error in my post from May 8):

-  _enterprise.spec_ : the localAS attribute's maximum value constraint should be 6**5**534 (not 64534)

**Comment by mfagadar** [comment]
Also for R5.1.1-U1:
- _uplinkconnection.spec_ : the type of the _uplinkID_ attribute should be **integer** instead of string

**Comment by pdellaert** [comment]
Going to close this for now, feel free to open a new issue if you find more required changes
