### ISSUE TITLE
DPIEnabled property of Nuage EnterpriseProfile specification

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#18]
Good day *,
[`enterpriseprofile.spec`](https://github.com/nuagenetworks/vsd-api-specifications/blob/4.0/enterpriseprofile.spec) has a DPIEnabled propery, though this property is missing in VSD

![image](https://cloud.githubusercontent.com/assets/5679861/25382403/21ebbefc-29c0-11e7-9409-d3eb5df86f12.png)

Moreover, seems like `enableApplicationPerformanceManagement` is used instead for DPI (in specs it has the same description for both properties). Where is the truth?

**Comment by pdellaert** [comment]
The truth is always in the API output/input you see. So i'm assuming the DPIEnabled property is obsolete/deprecated or renamed to enableApplicationPerformanceManagement. 

Let me check internally as well

**Comment by hellt** [comment]
Fixed in v5_0
