### ISSUE TITLE
BGPNeighbor and required attributes

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#19]
[BGPNeighbor](https://nuagenetworks.github.io/vsd-api-documentation/v4_0/bgpneighbor.html) object specifies `peerAS` as the only required attr.
Yet it seems like `name` and `peerIP` could be marked as required as well.
GUI app won't let create an object without specifying these 2 attrs.

**Comment by pdellaert** [comment]
Resolved in 5.0.2, for peerIP: the documentation itself states this is optional in case of an host vport, so this is not a required attribute
