### ISSUE TITLE
Inconsistency in Domain specification 

### ISSUE THREAD

**Issue by miguelagd** [nuagenetworks/vsd-api-specifications#20]
It seems to be an inconsistency in enum attribute `DHCPBehavior` of `Domain` specification: according to description of the attribute...

> "DHCPBehaviorType is an enum that indicates DHCP Behavior of VRS having VM's under this domain. Possible values are FLOOD, CONSUME ,RELAY"

... Possible values are `FLOOD`, `CONSUME` ,`RELAY`. However, the `Domain` specification defines the following values: `CONSUME`, `FLOOD`, `OVERLAY_RELAY`, `UNDERLAY_RELAY`. Furthermore, if one of the last two possibles values (i.e., `OVERLAY_RELAY` or `UNDERLAY_RELAY`) are used, Nuage returns an invalid parameter value error.

**Comment by pdellaert** [comment]
Resolved in 5.0.2
