### ISSUE TITLE
Inconsistency in uplinkconnection object

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#26]
Appears on 4.0.7(8), 5.0.1

1. Uplinkconnection object has no attrs marked as required in specs, though `mode` and `role` are required by VSD
2. 5.0.1 API has no `Any` mode for NSG uplink, specs still have Any stated in the enum.

**Comment by pdellaert** [comment]
Fixed in 5.1.1, thanks!
