### ISSUE TITLE
VLANRange should be required for RedundantPort obj

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#28]
[RedundantPort obj](https://nuagenetworks.github.io/vsd-api-documentation/v5_0/nsredundantport.html) does not qualify VLANRange attr as required, though omitting this attr leads to an error:

```json
                    "description": "VLAN Range specified null does not conform to a-b,c,d-f where a,b,c,d,f are integers between 0-4096.",
                    "title": "VLAN Range format specified is invalid."
    "internalErrorCode": 3315
``` 

Original POST:

![image](https://user-images.githubusercontent.com/5679861/26866393-917f8de6-4b69-11e7-8023-84b6306fb7ad.png)

**Comment by pdellaert** [comment]
Resolved in 5.0.2
