### ISSUE TITLE
Underlay object can not be POSTed to UplinkConnection?

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#29]
API v5.0 versions says that [Underlay](https://nuagenetworks.github.io/vsd-api-documentation/v5_0/underlay.html) object can be POSTed to UplinkConnection.
Though it seems that underlay object can be created only in PLATFORM settings

PS: Also `name` should be marked as `required`

**Comment by pdellaert** [comment]
resolved in 5.0.2
