### ISSUE TITLE
Static Route for L2 Domains?

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#30]
[L2Domain spec](https://github.com/nuagenetworks/vsd-api-specifications/blob/master/l2domain.spec#L980-L991) says a static route object can be a child.

> ![image](https://user-images.githubusercontent.com/5679861/27683773-e93c1ed8-5ccf-11e7-86fd-d88a703a2b93.png)

Though this is not working

**Comment by pdellaert** [comment]
resolved in 5.0.2
