### ISSUE TITLE
Default value for NATTraversal of nsport is wrong

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#39]
in 5.1.1 `NATTraversal` param receives `FULL_NAT` value by default, while the specs are not updated with this change https://nuagenetworks.github.io/vsd-api-documentation/v5_0/nsport.html#attr_NATTraversal

**Comment by pdellaert** [comment]
@hellt Thanks, did you verify this when doing an API call, or is this what you see in the UI? And if API, can you provide debug output at all of your API call and return? 

I'd like to document this change a bit :)

**Comment by hellt** [comment]
My test was as follows:
1. Create an nsg template with network  port template. Port template has no
NATTraversal attribute.
2. Instantiate NSG from this template. Nsport object coming from VSD has
FULL_NAT value for NATTraversal param which correlates with UI check box of
port instance. This is seen in json as well

**Comment by pdellaert** [comment]
Have to close this issue, the default is still None. The value is part of nsport for both network and access port (they both use the nsport construct). For network port, the default behaviour is now to enable FULL_NAT, but for access port, it hasn't.
