### ISSUE TITLE
staticroute specs miss OVERLAY_ADDRESS_TRANSLATION type

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#42]
@pdellaert hi,
[staticroute specs](https://github.com/nuagenetworks/vsd-api-specifications/blob/master/staticroute.spec#L223) has no allowed_choice of value "OVERLAY_ADDRESS_TRANSLATION".

This makes it impossible to programmatically create OAT scenarios

![image](https://user-images.githubusercontent.com/5679861/31574433-87d1859a-b0d8-11e7-9242-0c8f8c0a25d1.png)

**Comment by pdellaert** [comment]
Added in master for next release

**Comment by hellt** [comment]
Is 5.1.2 "the next release"?

**Comment by pdellaert** [comment]
yes, specs will be released later today/tomorrow

**Comment by hellt** [comment]
tested with 5.1.2
