### ISSUE TITLE
DHCPOption has no useful filterable attributes

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#44]
Hi all,
[DHCPOption spec](https://nuagenetworks.github.io/vsd-api-documentation/v5_0/dhcpoption.html) has no filterable unique attribute that would allow us to fetch a particular object.

`actualType` attribute (as I see it) could make quite a good candidate for that. Right now we can not fetch a particular option on the server side and are forced to fetch all DHCPOptions and in a loop looking for `actualType` we interested in.

Is it possible to put into consideration to make `actualType` a filterable attr?

**Comment by pdellaert** [comment]
`actualType` and `actualValues`, as far as i know, are not part of the database itself and are used only in the backend, meaning that filtering on them requires some backend changes which are bigger then just enable the field for filtering (new logic to be build to parse the filter, compared to the standard design).

Unless there is a serious need, for now, i'm going to close this (mail me if you have a concern)
