### ISSUE TITLE
vnfmetadata can not be created under Org

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#45]
Specs says that [vnfmetadata](https://nuagenetworks.github.io/vsd-api-documentation/v5_0/vnfmetadata.html) can be created under `/enterprise/id/` which seems to be untrue.
Workflow says that metadata is only defined at csproot level

**Comment by pdellaert** [comment]
@hellt, is it just create/post that fails, or also get?

**Comment by hellt** [comment]
no, GET operation works fine. Let me check, maybe POST operation is allowed as well, but just not used in workflows we have so far

**Comment by hellt** [comment]
Tested POST operation. Works as well, though in Architect vnfmetadatas created that way are not visible at all.
Could be either unintended POST operation, or it is part of a future VNF features.

**Comment by pdellaert** [comment]
Closing this, you can actually create this on an enterprise if you have the right enterprise profile (allowing VNF management)
