### ISSUE TITLE
overlaymirrordestination.spec has no children defined

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#46]
HI,
don't know if fixing specs will trigger vspk rebuild process, but I also put it as a spec issue. Children section - https://github.com/nuagenetworks/vsd-api-specifications/blob/master/overlaymirrordestination.spec#L225

Source of or related to https://github.com/nuagenetworks/vspk-python/issues/20

**Comment by pdellaert** [comment]
@hellt, what children are expected for overlaymirrordestination?

**Comment by hellt** [comment]
Cant say for the whole list, but `vports` must be (by analogy with redirection target)

**Comment by hellt** [comment]
tested with 5.1.2, issue is resolved there.
