### ISSUE TITLE
UplinkConnection.uplinkID constraints mismatch

### ISSUE THREAD

**Issue by mfagadar** [nuagenetworks/vsd-api-specifications#56]
In _uplinkconnection.spec_, the _uplinkID_ attribute value constraints are set as if the attribute is a string, with the length and value constraints swapped. 

Since the uplinkID is an integer, the **correct constraints** should be:

```
"max_length": null,
"max_value": 65535,
"min_length": null,
"min_value": 1,
```

The issue is found in several branches: 5.2.2, 5.3.1 etc.

**Comment by pdellaert** [comment]
Fixed in upstream, will come in 5.3.2, thanks @mfagadar
