### ISSUE TITLE
OSPFInstance exportLimit parameter marked as required

### ISSUE THREAD

**Issue by brncoguz** [nuagenetworks/vsd-api-specifications#61]
seems like `exportLimit` parameter is not a mandatory parameter but it's marked as `required`

architect sends that parameter as null:
![image](https://user-images.githubusercontent.com/11637526/45358436-12ebc100-b5d2-11e8-89b8-8ffc7300bae7.png)

**Comment by pdellaert** [comment]
Thanks, @brncoguz , sorry for the late reply, we'll look at it and fix this in our next release!
