### ISSUE TITLE
`infrastructureaccessprofile` object for v4_0 does not have `connectionendpoint` child leaf

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vsd-api-specifications#63]
v4_0 version of [infra access profile spec](https://github.com/nuagenetworks/vsd-api-specifications/blob/r4.0.11.2/infrastructureaccessprofile.spec) does not list `connectionendpoint` object in its children list

This prevents users from having source ip filters created via API.

When adding Source IP Filter in Architect v4 the connectionendpoint object is a child of IAP

/cc @pdellaert

**Comment by pdellaert** [comment]
Going to close this as we are no longer maintaining the v4 specs, really...
