### ISSUE TITLE
Looking for the availability date of release 6.0 specs

### ISSUE THREAD

**Issue by fvene** [nuagenetworks/vsd-api-specifications#64]
Not sure it is the right place to ask such a question, so my apologies in case it is not.
I have heard Nuage v6 is on its way and I would be interested to get the specs to better understand the differences between v5 and v6.
Many thanks in advance

**Comment by pdellaert** [comment]
Hi @fvene, 

Every releases's API specifications become publicly available when that release has been officially released. For more details on the release schedule, contact your Nuage/Nokia representative.

Regards,
